<h4> Inexact line search and descent direction</h4>

Name : Mukul Shingwani
<br>
Roll : B20AI023

<img src = "Screenshot 2022-11-16 141732.jpg">

In [1]:
import numpy as np
import math

In [2]:
beta1 = pow(10,-4)
beta2 = 0.9
r = 0.5
eps = pow(10,-3)

##Question 1
<h3>f : R2 → R is defined by f(x) = 0.5(100(x1 − x22)2 + (r − x1)2) with and x0 = (2r, −2r) where r is the last digit of your
roll number. If last digit of your roll number is 0 then choose r = 1.75. Find number of iterations, function evaluations and
gradient evaluations.

In [3]:
def func1(x):
  x1 = x[0]
  x2 = x[1]
  f_x = 0.5 * ((100 * (x1 - (x2**2))**2) + (3 - x1)**2)
  return f_x

In [4]:
def grad1(x):
  f0,n,h1=func1(x),len(x),pow(10,-5)
  g=np.zeros((n,1),dtype=float)
  for i in range(0,n):
    x1=x.copy()
    x1[i]=x1[i]+h1
    g[i]=(func1(x1)-f0)/h1
  return g


In [5]:
def find_descent1(x0,beta1,beta2,r,eps):
  iter1 = 0
  B0 = np.identity(2,dtype=float)
  countf = 0
  countg = 0
  f0 = func1(x0)
  g0 = grad1(x0)
  countf += 1
  countg += 1
  while np.linalg.norm(g0) > eps and iter1 < 1000:
    d0,alpha = -grad1(x0),1
    x1 = x0 + alpha*d0
    f1,g1=func1(x1),grad1(x1)
    countf += 1
    countg += 1
    while (f1 > f0+alpha*beta1*g0.T@d0 or np.dot(g1.T,d0)<beta2*np.dot(g0.T,d0)) and alpha>pow(10,-5):
      alpha=alpha*r
      x1 = x0 + alpha * d0
      f1, g1 = func1(x1), grad1(x1)
      countf += 1
      countg += 1
    x0,g0,iter1=x1,g1,iter1+1
  return x0,countf,countg,iter1


In [6]:
n = 2
x0_1 = [[6],[-6]]
x0_1 = np.array(x0_1,dtype=float)
x0_final1,func_count1,grad_count1,iters1 = find_descent1(x0_1,beta1,beta2,r,eps)

In [7]:
print("Number of iterations = {}".format(iters1))
print("Number of function evaluations = {}".format(func_count1))
print("Number of gradient evaluations = {}".format(grad_count1))


Number of iterations = 1000
Number of function evaluations = 11126
Number of gradient evaluations = 11126


In [8]:
x0_final1

array([[10.98819644],
       [ 4.47280978]])

##Question 2
<h4> Solve the above problem with descent direction at xk = −B∇f(xk) where B =[[2r, √r],[√r, r]] 
. Find number of iterations, function evaluations and gradient evaluations. Does this method take less number of iterations?

In [9]:
def find_descent2(x0, beta1, beta2, r, eps):
    iter1, B0, countf, countg = 0, [[6, pow(3,0.5)], [pow(3,0.5), 3]], 0, 0
    f0, g0 = func1(x0), grad1(x0)
    countf += 1
    countg += 1
    while np.linalg.norm(g0) > eps and iter1 < 1000:
        # d0,alpha = -grad1(x0), 1
        d0, alpha = -np.dot(np.linalg.inv(B0), g0), 1
        x1 = x0 + alpha*d0
        f1, g1 = func1(x1), grad1(x1)
        countf += 1
        countg += 1
        while (f1 > f0+alpha*beta1*g0.T@d0 or np.dot(g1.T,d0) < beta2*np.dot(g0.T,d0)) and alpha>pow(10,-5):
            alpha = alpha * r
            x1 = x0 + alpha * d0
            f1, g1 = func1(x1), grad1(x1)
            countf += 1
            countg += 1

        dt1, s1 = x1-x0, g1-g0
        # B0 = B0+1/(dt1.T@s1)*s1@s1.T-1/(s1.T@B0@s1)*B0@s1@s1.T@B0
        x0, g0, iter1 = x1, g1, iter1+1
    return x0, iter1, countf, countg

In [10]:
n = 2
x0_2 = [[6],[-6]]
x0_2 = np.array(x0_2,dtype=float)
x0_final2,func_count2,grad_count2,iters2 = find_descent2(x0_2,beta1,beta2,r,eps)

In [11]:
print("Number of iterations = {}".format(iters2))
print("Number of function evaluations = {}".format(func_count2))
print("Number of gradient evaluations = {}".format(grad_count2))

Number of iterations = 9519
Number of function evaluations = 1000
Number of gradient evaluations = 9519


In [12]:
x0_final2

array([[7.28954589],
       [4.69278764]])

NO, this method takes more number of iterations

##Question 3
<h4> Solve the above problem with descent direction at dk = −Bk−1∇f(xk) where B0 = I2 and Bk+1 = Bk +sks....

Find number of iterations, function evaluations and gradient evaluations.

Which method takes less number of iteration among three.?

In [13]:
def find_descent3(x0,beta1,beta2,r,eps):
  iter1 = 0
  B0 = np.identity(2,dtype=float)
  countf = 0
  countg = 0
  f0 = func1(x0)
  g0 = grad1(x0)
  countf += 1
  countg += 1
  while np.linalg.norm(g0) > eps and iter1 < 1000:
    d0,alpha = -np.dot(np.linalg.inv(B0),g0),1
    x1 = x0 + alpha*d0
    f1,g1=func1(x1),grad1(x1)
    countf += 1
    countg += 1
    while (f1 > f0+alpha*beta1*g0.T@d0 or np.dot(g1.T,d0)<beta2*np.dot(g0.T,d0)) and alpha>pow(10,-5):
      alpha=alpha*r
      x1 = x0 + alpha * d0
      f1, g1 = func1(x1), grad1(x1)
      countf += 1
      countg += 1
    dt1,s1=x1-x0,g1-g0
    B0 = B0+1/(dt1.T@s1)*s1@s1.T-1/(s1.T@B0@s1)*B0@s1@s1.T@B0
    x0,g0,iter1=x1,g1,iter1+1
  return x0,countf,countg,iter1

In [14]:
n = 2
x0_3 = [[6],[-6]]
x0_3 = np.array(x0_3,dtype=float)
x0_final3,func_count3,grad_count3,iters3 = find_descent3(x0_3,beta1,beta2,r,eps)

In [15]:
print("Number of iterations = {}".format(iters3))
print("Number of function evaluations = {}".format(func_count3))
print("Number of gradient evaluations = {}".format(grad_count3))

Number of iterations = 34
Number of function evaluations = 63
Number of gradient evaluations = 63


In [16]:
x0_final3

array([[2.9978298],
       [1.7314199]])

.

conclusion : Third Method takes the least number of iterations