<h3>Gradient Descent and stochastic gradient descent methods with quadratic polynomial</h3> 

<h3>Name : Mukul Shingwani
<br>
<h3>Roll : B20AI023

<img src = "Screenshot 2022-11-16 141553.jpg">

In [5]:
!pip install openpyxl

     ------------------------------------ 242.1/242.1 kB 822.4 kB/s eta 0:00:00


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h2>Question 1

<img src ="Screenshot 2022-11-16 130436.jpg">

In [6]:
data=pd.read_excel('car_price.xlsx')
data.head()

wheelbase  carlength  carwidth  carheight  boreratio    price
0       88.6      168.8      64.1       48.8       3.47  13495.0
1       88.6      168.8      64.1       48.8       3.47  16500.0
2       94.5      171.2      65.5       52.4       2.68  16500.0
3       99.8      176.6      66.2       54.3       3.19  13950.0
4       99.4      176.6      66.4       54.3       3.19  17450.0

In [7]:
x1,y1=data.values[:,0:-1],data.values[:,-1]


In [8]:
def func(x):
    n=len(x1)
    sum=0
    # print(x1[0].T.shape, x.shape, y1[0].shape)
    for i in range(n):
        temp=(np.dot(x1[i].T, x)- y1[i])**2
        # print(temp)
        sum += temp
    sum=sum/(2*n)
    return sum

def grad(x):
    n=len(x1)
    sum=np.array([0.0, 0.0, 0.0, 0.0, 0.0])
    for i in range(n):
        sum+=np.dot(x1[i], (np.dot(x1[i].T, x)- y1[i]))
    sum=sum/n
    return sum

print(func(np.array([0, 0, 0, 0, 0])))

119890739.74557047


In [9]:
epsilon=1e-2
x0=np.array([0,0,0,0,0],dtype=float)
b1=1e-4
b2=0.9
r=0.5
i=0
a=1
no_itr=0
of_v=[]
of_v.append(func(x0))
while (np.linalg.norm(grad(x0))>epsilon) and no_itr<2000:
    d0=-grad(x0)
    no_itr=no_itr+1
    argimo_val=b1*a*(np.dot(grad(x0).reshape(1,-1),d0.reshape(-1,1)))
    a=1
    while((func(x0+a*d0)>= func(x0)+b1*a*(np.dot(grad(x0).T,d0))) or (np.dot(grad(x0+a*d0).T,d0)<=b2*(np.dot(grad(x0).T,d0)))):
        a=a*r
    print()
    print(a)
    x0=x0+a*d0
    print("objective function value : "+ str(func(x0)))
    of_v.append(func(x0))
    print(x0)

print("no of itr : " +str(no_itr))


3.0517578125e-05
objective function value : 46245716.72725863
[40.85766678 72.56416473 27.0992576  21.83861839  1.38547629]

3.0517578125e-05
objective function value : 31430408.527262945
[22.35587031 40.42529128 14.65193154 11.44647611  0.77056598]

3.0517578125e-05
objective function value : 28443624.49701335
[30.47105203 55.23518126 19.93750364 15.50688676  1.05263177]

3.0517578125e-05
objective function value : 27835134.017952625
[26.65127171 48.99298382 17.27178501 13.08699605  0.93249273]

3.0517578125e-05
objective function value : 27704839.2888008
[28.18326584 52.1903627  18.17159687 13.573121    0.99270316]

3.0517578125e-05
objective function value : 27670699.71675322
[27.31564084 51.15481915 17.4727826  12.75642561  0.97204501]

6.103515625e-05
objective function value : 27666655.97498351
[27.73262092 52.87941729 17.50912979 12.29188824  1.00325252]

3.0517578125e-05
objective function value : 27639236.841912158
[26.97629412 52.03931691 16.88463072 11.53598504  0.98633718]

In [10]:
def value(r, R):
    val1=R+(0.1*r)
    val2=100+(R+0.2*r)
    val3=0.1*r+(R-1)
    val4=54.3
    val5=r+(0.01*R)
    return np.array([val1, val2, val3, val4, val5])

print(value(3, 23))
print(np.dot(x0.T, value(3, 23)))

[ 23.3  123.6   22.3   54.3    3.23]
9161.443558848863


<h2> Question 2
<h4> Write code for stochastic gradient for the above problem with 10 random points in every iterations with 100 iterations. Estimate
the price of a car with inputs ˆa = (R.r, 100 + R.2r,(R − 1).r, 54.3, r.R)

In [11]:
# "/content/drive/MyDrive/Optimization_in_ML_labs/lab7/Concrete_Data_Yeh.csv"

In [12]:
data=pd.read_excel("car_price.xlsx")
x15,y15=data.values[:,0:-1],data.values[:,-1]

In [13]:
import random
temp=[]
list1=range(len(x15))
for i in range(10):
    temp.append(random.choice(list1))
x1 ,y1=data.values[temp,0:5],data.values[temp,5]


In [14]:
def func(x):
    n=len(x1)
    sum=0
    # print(x1[0].T.shape, x.shape, y1[0].shape)
    for i in range(n):
        # print(x1[i].T, x, y1[i])
        temp=(np.dot(x1[i].T, x)- y1[i])**2
        print(temp)
        sum += temp
    sum=sum/(2*n)
    return sum

def grad(x):
    n=len(x1)
    sum=np.array([0.0, 0.0, 0.0, 0.0, 0.0])
    for i in range(n):
        sum+=np.dot(x1[i], (np.dot(x1[i].T, x)- y1[i]))
    sum=sum/n
    return sum
# f=np.array([0, 0, 0, 0, 0])
# print(func(f))

In [15]:
epsilon=0.01
x0=np.array([0,0,0,0,0],dtype=float)
b1=0.0001
b2=0.9
r=0.5
i=0
a=1
no_itr=0
of_v=[]
of_v.append(func(x0))
while (np.linalg.norm(grad(x0))>epsilon):
    d0=-grad(x0)
    
    if(no_itr==100):
        break
    no_itr=no_itr+1
    argimo_val=b1*a*(np.dot(grad(x0).reshape(1,-1),d0.reshape(-1,1)))

   
    temp=[]
    for i in range(10):
        temp.append(random.choice(list1))

    x1,y1=data.values[temp,0:5],data.values[temp,5]
    a=1
    while((func(x0+a*d0)> func(x0)+b1*a*(np.dot(grad(x0).T,d0))) or (np.dot(grad(x0+a*d0).T,d0)<b2*(np.dot(grad(x0).T,d0)))):

        a=a*r
    x0=x0+a*d0
    print("objective function value : "+ str(func(x0)))
    of_v.append(func(x0))
    print(x0)

print("no of itr : " +str(no_itr))

53217025.0
136749636.0
90155025.0
207331201.0
283754025.0
484792324.0
67158025.0
86397025.0
119793025.0
194602500.0
3.510096645492231e+17
3.5969237634114266e+17
3.189117292766356e+17
3.0661904627592704e+17
3.409575808429315e+17
3.0313403472503264e+17
4.119148775310586e+17
4.486665014871617e+17
2.8120076193136522e+17
4.0179234901885235e+17
97911025.0
126517504.0
99600400.0
134444025.0
168065296.0
37149025.0
1706929225.0
291555625.0
42627841.0
272745225.0
8.774948496253915e+16
8.991972115895272e+16
7.972511437777989e+16
7.665155134174966e+16
8.523561031098123e+16
7.578183080990051e+16
1.0296546170308363e+17
1.1216090680755461e+17
7.029845938248445e+16
1.0044285313373974e+17
97911025.0
126517504.0
99600400.0
134444025.0
168065296.0
37149025.0
1706929225.0
291555625.0
42627841.0
272745225.0
2.193590568996811e+16
2.247824387401577e+16
1.992986966110562e+16
1.916128277223788e+16
2.130701019089397e+16
1.894461878072718e+16
2.573473722602885e+16
2.8037367529104096e+16
1.7573749311428122e+16
2.

In [16]:
print(np.dot(x0.T, value(3,23)))

8506.469997145377


#<h2>Question 3
<h4>Consider the’‘Concrete Data Yeh” data set. Write code for best fitting quadratic polynomial using gradient descent method.
Choose stopping condition ∥∇f(x)∥ < 0.01.</h4>

In [17]:
data2 = pd.read_csv("Concrete_Data_Yeh.csv")
data2.head()

cement   slag  flyash  water  superplasticizer  coarseaggregate  \
0   540.0    0.0     0.0  162.0               2.5           1040.0   
1   540.0    0.0     0.0  162.0               2.5           1055.0   
2   332.5  142.5     0.0  228.0               0.0            932.0   
3   332.5  142.5     0.0  228.0               0.0            932.0   
4   198.6  132.4     0.0  192.0               0.0            978.4   

   fineaggregate  age  csMPa  
0          676.0   28  79.99  
1          676.0   28  61.89  
2          594.0  270  40.27  
3          594.0  365  41.05  
4          825.5  360  44.30

In [18]:
x_data = data2.iloc[:,:-1].values
y_data = data2.iloc[:,-1].values

In [19]:
def find_mult(var,x_data):
  val = var[len(var)-1]
  for i in range(8,0,-1):
    val += pow(x_data[len(x_data)-i],i) * var[len(x_data)-i]
  return val
#function to find the value of f(beta)
def func2(x_data,y_data,var):
  f = 0.0
  for i in range(len(x_data)):
    f += pow(find_mult(var,x_data[i]) - y_data[i],2)
  f = f / (2 * len(x_data))
  return f

In [20]:
#function to find the value of gradient of f(beta)
def grad_f2(x_data,y_data,var):
  n = len(x_data)
  grad = np.array([0]*9,dtype=float)

  for j in range(8):
    for i in range(n):
      grad[j] += (8 - j) * pow(x_data[i][j],(8 - j -1)) \
      * (find_mult(var,x_data[i]) - y_data[i])
    grad[j] = grad[j] / n

  for i in range(n):
    grad[8] += (find_mult(var,x_data[i]) - y_data[i])
  grad[8] = grad[8] / n
  return grad

In [21]:
#initializing the initial values and constraints
var = np.array([0]*9,dtype=float)
beta_1 = 1e-4
beta_2 = 0.9
r= 0.5
epsilon = 0.01
iter = 0

f0 = func2(x_data,y_data,var)
g0 = grad_f2(x_data,y_data,var)

# Minimizing the loss function using gradient descent
while(np.linalg.norm(g0) > epsilon and iter < 1000):
  d0, alpha = -1*g0, 1
  f1 = func2(x_data,y_data,var + (alpha * d0))
  g1 = grad_f2(x_data,y_data,var + (alpha * d0))

  # finding optimal value of alpha
  while (f1 > f0 + (alpha * beta_1 * g0.T@d0) or 
         np.dot(g1.T, d0) < (beta_2 * np.dot(g0.T, d0))):
    alpha = alpha * r
    f1 = func2(x_data,y_data,var + alpha * d0)
    g1 = grad_f2(x_data,y_data,var + alpha * d0)

  iter = iter +1
  var += alpha * d0
  f0 = f1
  g0 = g1

KeyboardInterrupt: 

In [ ]:
print(var)
print("Function value --> ", func2(x_data,y_data,var))
print("Number of iterations --> ",iter)

<h2>Question 4
<h4>Write code for stochastic gradient for the above problem with 20 random points in every iterations.

In [22]:
#initializing the initial values and constraints
var1 = np.array([0]*9,dtype=float)
beta_1 = 1e-4
beta_2 = 0.9
r= 0.5
epsilon = 0.01
iter = 0

f0 = func2(x_data,y_data,var1)

# Minimizing the loss function using stochastic gradient descent
while(iter < 100):
  # selecting random 10 data points to calculate gradient
  temp_data = data2.sample(frac = 0.019)
  x_data2 = temp_data.iloc[:,:-1].values
  y_data2 = temp_data.iloc[:,-1].values
  g0 = grad_f2(x_data2,y_data2,var1)

  d0 = -1*g0
  alpha = 1/(iter + 1)
  f1 = func2(x_data,y_data,var1 + (alpha * d0))
  if(f1 < f0):
    var1 += alpha * d0
    f0 = f1
  iter = iter+1

In [23]:
print(var)
print("Function value --> ", func2(x_data,y_data,var1))
print("Number of iterations --> ",iter)

[1.43703028e-20 3.24059737e-24 1.44383289e-27 6.47405653e-29
 5.15405449e-35 3.22792732e-32 1.78608008e-35 1.14925108e-38
 1.14925108e-38]
Function value -->  780.8686016504852
Number of iterations -->  100


<center> ------------------------------------------------------------------------------ END ------------------------------------------------------------------------</center>